import { use } from "react";
import { Metadata } from "next";
import PlayerClient from "./PlayerClient";

type Props = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  
  return {
    title: `Your Morning Recap | Inbox FM`,
    description: "Listen to your personalized email summary generated by AI.",
    openGraph: {
      title: `Your Morning Recap | Inbox FM`,
      description: "Listen to your personalized email summary generated by AI.",
      images: ['/images/og-image.png'],
    },
  };
}

export default function PlayerPage({ params }: Props) {
    const { id } = use(params);
    return <PlayerClient id={id} />;
}
